export const SET_INITIAL_STATE = 'SET_INITIAL_STATE'
export const DELETE_COMPANY_BY_ID = 'DELETE_COMPANY_BY_ID'
export const SORT_COMPANIES = 'SORT_COMPANIES'
export const ADD_COMPANY = 'ADD_COMPANY'
